#!/usr/bin/with-contenv bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first

if ! command -v borgmatic; then
    echo "**** Adding borgmatic and ssh to package install lists ****"

    # borgmatic *should* install borgbackup automatically
    echo "borgmatic" >> /mod-repo-packages-to-install.list
    ## Ubuntu
    if [ -f /usr/bin/apt ]; then
        echo "\
            openssh-client" >> /mod-repo-packages-to-install.list
    fi
    # Alpine
    if [ -f /sbin/apk ]; then
        echo "\
            openssh" >> /mod-repo-packages-to-install.list
    fi
else
    echo "**** borgmatic already installed, skipping ****"
fi

# setting default environment variables- they must be added before main mod script runs
echo -n "${BORGMATIC_ENCRYPTION:-none}" > /run/s6/container_environment/BORGMATIC_ENCRYPTION
echo -n "${BORGMATIC_PERIODIC:-daily}" > /run/s6/container_environment/BORGMATIC_PERIODIC
echo -n "${BORGMATIC_ROOT:-/config}" > /run/s6/container_environment/BORGMATIC_ROOT
echo -n "${BORGMATIC_SOURCE:-/config}" > /run/s6/container_environment/BORGMATIC_SOURCE
echo -n "${BORGMATIC_REPO:-/tmp/borgmatic-backup}" > /run/s6/container_environment/BORGMATIC_REPO
echo -n "${BORGMATIC_PASSPHRASE:-XYZl0ngandsecurepa_55_phrasea&&123}" > /run/s6/container_environment/BORGMATIC_PASSPHRASE

# "${BORGMATIC_RESTORE:=latest}"
