#!/usr/bin/with-contenv bash

export BORG_SOURCE_DIRECTORY="${BORG_SOURCE_DIRECTORY:=/config}"
export BORG_REPO="${BORG_REPO:=/tmp/borgmatic-backup}"

mkdir -p ${BORG_SOURCE_DIRECTORY}
mkdir -p ${BORG_REPO}

chmod 750 -R ${BORG_REPO}

lsiown -R abc:abc ${BORG_REPO}

echo "Validating configuration..."

exec s6-setuidgid abc borgmatic config validate --config /config/borgmatic.yaml

if [ -z ${BORG_REPO_KEY+x} ]; 
then 
  echo "No repo key set; repo will be unencrypted"; 
  exec s6-setuidgid abc borgmatic rcreate --encryption none --config /config/borgmatic.yaml
else 
  echo "Repo key set; repo will be encrypted"; 
  exec s6-setuidgid abc borgmatic rcreate --encryption repokey-aes-ocb --config /config/borgmatic.yaml
fi
