#!/usr/bin/with-contenv bash

# make borgmatic config directories
mkdir -p ${BORGMATIC_ROOT}/.config/borgmatic/ ${BORGMATIC_ROOT}/.config/borg/

# copy default config files if they don't exist
if [[ ! -f ${BORGMATIC_ROOT}/.config/borgmatic/config.yaml ]]; then
    cp /defaults/config.yaml.sample ${BORGMATIC_ROOT}/.config/borgmatic/config.yaml
fi

# if an ssh private key is found for borgmatic, change its mode
if [[ -e ${BORGMATIC_SSH_KEY} ]]; then
#  lsiown abc:abc ${BORGMATIC_SSH_KEY}
  chmod 600 ${BORGMATIC_SSH_KEY}    
fi

# rather than deal with root crontabs and their possible conflicts with other containers (i.e, swag),
# we're using alpine's /etc/periodic cron run-parts scripts
# periodic can be: 15min, hourly, daily, weekly, or monthly
cp /app/borgmatic-backup /etc/periodic/${BORGMATIC_PERIODIC}
chmod +rx /etc/periodic/${BORGMATIC_PERIODIC}/borgmatic-backup

# permissions
lsiown -R abc:abc /config

chmod +r ${BORGMATIC_ROOT}/.config/borgmatic/config.yaml

echo "Validating configuration..."

borgmatic config validate --config ${BORGMATIC_ROOT}/.config/borgmatic/config.yaml

backup_exit=2

while [ ${backup_exit} -ne 0 ];
do
  echo "Borg repo encryption mode set to ${BORGMATIC_ENCRYPTION}";
  borgmatic rcreate --encryption ${BORGMATIC_ENCRYPTION} --config ${BORGMATIC_ROOT}/.config/borgmatic/config.yaml --make-parent-dirs
  backup_exit=$?
done

echo "Running initial backup..."
# run initial IP update
exec s6-setuidgid root /app/borgmatic-backup
