#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then
    ## Ubuntu
    echo "\
        borgbackup \
        borgmatic \
        openssh-client" >> /mod-repo-packages-to-install.list
fi

if [ -f /sbin/apk ]; then
    # Alpine
    echo "\
        borgbackup \
        borgmatic \
        openssh" >> /mod-repo-packages-to-install.list
fi

# copy default config files if they don't exist
if [[ ! -f /config/borgmatic.yaml ]]; then
    cp /defaults/borgmatic.yaml.sample /config/borgmatic.yaml
fi

# permissions
lsiown -R abc:abc \
    /app \
    /config

lsiown root:root /config/crontabs/root
chmod +rx /config/borgmatic.yaml
chmod +rx /config/crontabs/root
