#!/usr/bin/with-contenv bash

# default environment variables
echo -n "${BORGMATIC_ENCRYPTION:-none}" > /run/s6/container_environment/BORGMATIC_ENCRYPTION
echo -n "${BORGMATIC_PERIODIC:-daily}" > /run/s6/container_environment/BORGMATIC_PERIODIC
echo -n "${BORGMATIC_ROOT:-/config}" > /run/s6/container_environment/BORGMATIC_ROOT
echo -n "${BORGMATIC_SOURCE:-/config}" > /run/s6/container_environment/BORGMATIC_SOURCE
echo -n "${BORGMATIC_REPO:-/tmp/borgmatic-backup}" > /run/s6/container_environment/BORGMATIC_REPO
echo -n "${BORGMATIC_PASSPHRASE:-XYZl0ngandsecurepa_55_phrasea&&123}" > /run/s6/container_environment/BORGMATIC_PASSPHRASE

# "${BORGMATIC_RESTORE:=latest}"

# install packages
if [ -f /usr/bin/apt ]; then
    ## Ubuntu
    echo "\
        borgbackup \
        borgmatic \
        openssh-client" >> /mod-repo-packages-to-install.list
fi

if [ -f /sbin/apk ]; then
    # Alpine
    echo "\
        borgbackup \
        borgmatic \
        openssh" >> /mod-repo-packages-to-install.list
fi
