#!/usr/bin/with-contenv bash

# default environment variables
"${BORGMATIC_ENCRYPTION:=none}" > /run/s6/container_environment/BORGMATIC_ENCRYPTION
"${BORGMATIC_PERIODIC:=daily}" > /run/s6/container_environment/BORGMATIC_PERIODIC
"${BORGMATIC_ROOT:=/config}" > /run/s6/container_environment/BORGMATIC_ROOT
"${BORGMATIC_SOURCE:=/config}" > /run/s6/container_environment/BORGMATIC_SOURCE
"${BORGMATIC_REPO:=/tmp/borgmatic-backup}" > /run/s6/container_environment/BORGMATIC_REPO

# "${BORGMATIC_RESTORE:=latest}"

# install packages
if [ -f /usr/bin/apt ]; then
    ## Ubuntu
    echo "\
        borgbackup \
        borgmatic \
        openssh-client" >> /mod-repo-packages-to-install.list
fi

if [ -f /sbin/apk ]; then
    # Alpine
    echo "\
        borgbackup \
        borgmatic \
        openssh" >> /mod-repo-packages-to-install.list
fi
